# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180219_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='main.Message'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.User'),
        ),
    ]
