# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=-1),
        ),
    ]
