# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ninja',
            name='dojo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dojo', to='dojo_ninjas.Dojo'),
            preserve_default=False,
        ),
    ]
